etapasProject/etapasApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'etapasApp'

urlpatterns = [
	path('', views.IndexView, name =  "index"),

	path('trayectoria/', views.TrayectoriaView, name='trayectoria' ),
	path('trayectoria/<int:curso_id>', views.TrayectoriaView, name =  "trayectoria_id"),
	path('actualizarStepElement/<int:curso_id>/<int:step_id>/', views.ActualizarStepElement.as_view(), name='actualizar'),
	path('carga_trayectoria/', views.CargaTrayectoriaView, name='carga-trayectoria'),
	]

etapasProject/etapasProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('etapasApp.urls')),
]

etapasProject/etapasApp/forms.py
from django import forms
from django.db.models import Q
import datetime
from .models import *

class StepElementForm(forms.ModelForm):
	class Meta:
		model=StepElement
		fields = (
        'path_step',
        'order'
        )
		widgets = {					
			'path_step':forms.TextInput(attrs={'class': 'form-control'}),
			'order':forms.TextInput(attrs={'class': 'form-control'})			
			}

class ReaderForm(forms.ModelForm):
    class Meta:
        model = Reader
        fields = ['file', 'file2']

etapasProject/etapasApp/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect
from .models import *
from .forms import *
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import MultipleObjectsReturned
import chardet
import pandas as pd
import os
import datetime
from datetime import date

# Create your views here.
def IndexView(request):
	cursos_guardados = Course.objects.all()
	return render (request, 'etapasApp/index.html', {'cursos_guardados': cursos_guardados})


def TrayectoriaView(request, curso_id):

	cursos_guardados = Course.objects.all()

	curso_1 = Course.objects.get(id=curso_id)
	print("curso_1: ", curso_1.name)

	try:
		path_id_del_curso = Path.objects.filter(course=curso_1.id)
		#print("path_id_del_curso.id: ", path_id_del_curso.id)
	except (Path.DoesNotExist, MultipleObjectsReturned) as e:
		return redirect('etapasApp:index')
	paths = Path.objects.all()
	path_steps = PathStep.objects.all()
	step_elements = StepElement.objects.all()
	evaluations = Evaluation.objects.all()
	courses = Course.objects.all()
	enterprises = Enterprise.objects.all()
	competences = Competence.objects.all()
	evaluation_competences = EvaluationCompetence.objects.all()
	course_competences = CourseCompetence.objects.all()
	path_step_y_number =[]


	for indx, pid in enumerate(path_id_del_curso):
		path_step_ids_del_path = PathStep.objects.filter(path = pid.id)
		print("path_step_ids_del_path.ids: ")

		

		

		for index, path_step_id in enumerate(path_step_ids_del_path):
			path_step_y_number.append([path_step_id.id, path_step_id.number])
			print("renglon numero : "+str(index)+" id = " +str(path_step_id.id)+ " num = "+str(path_step_id.number))
			step_element = StepElement.objects.filter(path_step = path_step_id.id)
			for index2, step_ele in enumerate(step_element):
				try:
					evaluation = Evaluation.objects.get(id = step_ele.evaluation_id )
					print("evaluacion = "+str(evaluation.name))
				except Evaluation.DoesNotExist:
					course = Course.objects.get(id = step_ele.course_id)
					print("course = "+str(course.name))
	return render (request, 'etapasApp/trayectoria.html', {'cursos_guardados': cursos_guardados, 'curso_1':curso_1, \
		'path_id_del_curso':path_id_del_curso , 'path_steps':path_steps , \
		'step_elements':step_elements, 'evaluations': evaluations, 'path_step_y_number':path_step_y_number, 'courses': courses,\
		'enterprises': enterprises, 'competences': competences, 'paths': paths, 'evaluation_competences': evaluation_competences,\
		'course_competences': course_competences})

def CargaTrayectoriaView(request):
    lista_verificacion = []
    lista_verificacion_BD = []
    valido = True 
    valido2 = True
    if request.method == 'POST':
        form = ReaderForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            

            #--------------preguntas del archivo nuevo a cargar
            file = form.cleaned_data.get('file')# archivo preguntas
            file2 = form.cleaned_data.get('file2')# archivo config
            obj = form.save(commit=False)
            #print("type(file): ", type(file))
            obj.file = file
            obj.file2 = file2
            obj.save()

            #f = obj.file.open('r')
            #reader_file = csv.reader(open(obj.file.path,'r'))
            with open(obj.file.path, 'rb') as f:
                result = chardet.detect(f.read())  # or readline if the file is large
            with open(obj.file2.path, 'rb') as f2:
                result2 = chardet.detect(f2.read())  # or readline if the file is large

            #pd.read_csv('filename.csv', )
            df = pd.read_csv(open(obj.file.path,'rb'), encoding=result['encoding'])#archivo de preguntas
            dffile2 = pd.read_csv(open(obj.file2.path,'rb'), encoding=result2['encoding'])# archivo de config
            print("type(df.columns): ", type(df.columns))
            print("dffile2.columns: ", dffile2.columns.all)
            columnas_config = ['Nombre Diagnostico', 'Competence ID', 'Competence', 'Name Perfil', 'Description', 'Instructions', 'Min score', 'Default attempts',\
            'Weight', 'Evaluation rule', 'Method Rule', 'Evaluation type', 'Diagnostic points']
            columnas_preg = ['ID Pregunta', 'Código', 'ID Competencia', 'Competencia','Prerrequisitos', 'Módulo', 'Tipo de Evaluación', 'Concepto',\
            'Tipo de ejercicio', 'Puntaje', 'Nivel', 'Instrucción', 'Descripción', 'Respuesta', 'Ponderación', 'Respuesta.1', 'Ponderación.1',\
            'Respuesta.2', 'Ponderación.2', 'Respuesta.3', 'Ponderación.3', 'Feedback', 'Recurso - Nombre', 'Recurso - URL', 'Idioma', 'Recurso - Nombre.1', \
            'Recurso - URL.1', 'Idioma.1', 'Recurso - Nombre.2', 'Recurso - URL.2', 'Idioma.2', 'Instrucciones del módulo']
            if columnas_config == dffile2.columns.tolist():
                print("columnas de config iguales")
            else:
                valido = False
                open(obj.file.path,'r').close()
                open(obj.file2.path,'r').close()
                os.remove(obj.file.path)
                os.remove(obj.file2.path)
                return render(request, 'etapasApp/carga_trayectoria.html',{'form': form, 'valido': valido, 'valido2': valido2, 'lista_verificacion' : lista_verificacion, 'lista_verificacion_BD' : lista_verificacion_BD})

            if columnas_preg == df.columns.tolist():
                print("columnas de preguntas iguales")
            else:
                valido2 = False
                open(obj.file.path,'r').close()
                open(obj.file2.path,'r').close()
                os.remove(obj.file.path)
                os.remove(obj.file2.path)
                return render(request, 'etapasApp/carga_trayectoria.html',{'form': form, 'valido': valido, 'valido2': valido2, 'lista_verificacion' : lista_verificacion, 'lista_verificacion_BD' : lista_verificacion_BD})

            #------EMPIEZA LECTURA DEL ARCHIVO DE CONFIG

            #------------------CARGA DE TABLA COURSE DEL ARCHIVO DE CONFIG-----------
            course_name = dffile2.iloc[0][3]
            existe_course = Course.objects.filter(name=course_name).exists()
            print("existe_course", existe_course)

            if not existe_course:                
                course_name = dffile2.iloc[0][3]
                course_short_name_list = [ s[0]+s[1]+s[2] if len(s) >= 3 else s[0] for s in course_name.split() ]
                course_short_name = ''.join(course_short_name_list).upper()
                course_created_at = datetime.datetime.now()
                course_updated_at = datetime.datetime.now()

            #------TERMINA LECTURA DEL ARCHIVO DE CONFIG
            open(obj.file.path,'r').close()
            open(obj.file2.path,'r').close()
            os.remove(obj.file.path)
            os.remove(obj.file2.path)
            return render(request, 'etapasApp/carga_trayectoria.html',{'form': form, 'valido': valido, 'valido2': valido2, 'lista_verificacion' : lista_verificacion, 'lista_verificacion_BD' : lista_verificacion_BD})
            
            



    else:
        form = ReaderForm()
        return render(request, 'etapasApp/carga_trayectoria.html',{'form': form, 'valido': valido, 'valido2': valido2, 'lista_verificacion' : lista_verificacion, 'lista_verificacion_BD' : lista_verificacion_BD})

class ActualizarStepElement(UpdateView):
    model = StepElement
    form_class = StepElementForm
    template_name = 'etapasApp/modM.html'
    #success_url = reverse_lazy('etapasApp:trayectoria')

    def get_success_url(self):
          # if you are passing 'pk' from 'urls' to 'DeleteView' for company
          # capture that 'pk' as companyid and pass it to 'reverse_lazy()' function
         cursoid=self.kwargs['curso_id']
         print("cursoid:",cursoid)
         return reverse('etapasApp:trayectoria_id', kwargs={"curso_id": self.kwargs['curso_id']})

    def get_object(self):
    	print("dfd", self.request.POST.get('pk'))
    	obj = get_object_or_404(StepElement, id=self.kwargs['step_id'])
    	print(obj)
    	return obj

    def get_context_data(self, **kwargs):
        context = super(ActualizarStepElement, self).get_context_data(**kwargs)
        context['curso_1'] = Course.objects.get(id=self.kwargs['curso_id']) #whatever you would like
        return context

    def form_valid(self, form):
        form.instance.save()
        return super().form_valid(form)

etapasProject/etapasApp/templates/etapasApp/carga_trayectoria.html
{% extends 'etapasApp/index.html' %}
{% load static %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="//cdn.datatables.net/select/1.3.4/css/select.dataTables.min.css">
  <style>
    
    .frase{
      
      
      color: white; 
      
      font-size: 30px;

    }
    .abajo{
      position: absolute;
      top:70%;
      width: 100%;
    }
    .text-abajo{
      color:white;
      font-size: 20px;
    }

  </style>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <title>Thincrs</title>

    <!-- Bootstrap CSS CDN -->


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous"/>
    
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'etapasApp/css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'etapasApp/css/stylesFacturacion.css' %}">




     <script>
        $( document ).ready(function() {
           $('.leftmenutrigger').on('click', function(e) {
           $('.side-nav').toggleClass("open");
           $(".ico-nav").toggle();
           e.preventDefault();
          });

          $("#session").click(function(){
            $(".session-item").toggle();
             $('#session').toggleClass("open-session");
          });
          $("#cursos").click(function(){
            $(".cursos-item").toggle();
             $('#cursos').toggleClass("open-cursos");
          });
          
      });


    </script>

</head>

<body>
        

          <!--contenido-->
            <div class="container-fluid">

                {% block content %}
                <!--breadcumb-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Inicio</a></li>
        <li class="breadcrumb-item"><a href="#">Cursos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Prueba de carga de trayectorias</li>
</nav>

<h1 class="text-center">Validación de carga de trayectorias de tipo evaluación</h1>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body card-form">
                <form method='POST' enctype="multipart/form-data" onsubmit="ShowLoading()">
                    {% csrf_token %}
                    <div class="row">
                       {{ form.as_p }}
                       <button type="submit" class="btn btn-master">Enviar</button>
                    </div>
                    {% if not valido %}
                    <h4>El archivo de cofig esta mal en formato.</h4>
                    {% endif %}
                    {% if not valido2 %}
                    <h4>El archivo de preguntas esta mal en formato.</h4>
                    {% endif %}

                    {% if lista_verificacion %}
                    <h4>Comparación con preguntas en el mismo archivo csv</h4>
                        {% for pregunta in lista_verificacion %}
                        
                            <p>Verificar la pregunta {{ pregunta.0 }} en renglón {{ pregunta.1 }} con renglón {{pregunta.2}}</p>
                        {% endfor %}
                    {% endif %}

                    {% if lista_verificacion_BD %}
                    <h4>Comparación con preguntas en la BD</h4>
                        {% for preguntaBD in lista_verificacion_BD %}
                            
                            <p>Verificar la pregunta {{ preguntaBD.0 }} en renglón {{ preguntaBD.1 }} con renglón {{preguntaBD.2}} <br> {{preguntaBD.3}} </p>
                        {% endfor %}
                    {% endif %}

                </form>
               
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function mostrarContrasena(){
      var tipo = document.getElementById("password");
        if(tipo.type == "password"){
        tipo.type = "text";
        }else{
        tipo.type = "password";
        }
    }

    function ShowLoading(e) {
        var div = document.createElement('div');
        var img = document.createElement('img');
        div.innerHTML = "Cargando...<br />";
        div.style.cssText = 'position: fixed; top: 40%; left: 50%; z-index: 5000; width: 10%; text-align: center; background: rgba(76, 175, 80, 0.01); border: 0px solid #000';
        div.appendChild(img);
        document.body.appendChild(div);
        return true;
        // These 2 lines cancel form submission, so only use if needed.
        //window.event.cancelBubble = true;
        //e.stopPropagation();
    }

</script>
                {% endblock content %}


            </div>


        </div>
        
        <div class="modal fade" id="edicion" role="dialog">
         
    
        </div>

<script type="text/javascript">
    function abrir_modal_edicion(url){
      
        $('#edicion').load(url, function (){
            $(this).modal('show');
        });
    };
    function abrir_modal_creacion(url){
        $('#creacion').load(url, function (){
            $(this).modal('show');
        });
    }
    

</script>

</body>

</html>

etapasProject/etapasApp/templates/etapasApp/modM.html
<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title">Edición de step {{ curso_1.id }} </h2>
			<button class="close" type="button" data-dismiss = "modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		<form method="POST" action="{% url 'etapasApp:actualizar' curso_1.id object.id %}">
			{% csrf_token %}
			<div class="modal-body">
			{{ form.as_p}}
			</div>
			<div class="modal-footer">
				<button class="btn btn-danger" type="button" data-dismiss = "modal">Cancelar</button>
				<button class="btn btn-primary" type="submit">Confirmar</button>
			</div>
		</form>
	</div>
</div>

etapasProject/etapasApp/templates/etapasApp/trayectoria.html
{% extends 'etapasApp/index.html' %}
{% load static %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="//cdn.datatables.net/select/1.3.4/css/select.dataTables.min.css">
  <style>
    
    .frase{
      
      
      color: white; 
      
      font-size: 30px;

    }
    .abajo{
      position: absolute;
      top:70%;
      width: 100%;
    }
    .text-abajo{
      color:white;
      font-size: 20px;
    }

  </style>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <title>Thincrs</title>

    <!-- Bootstrap CSS CDN -->


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous"/>
    
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'etapasApp/css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'etapasApp/css/stylesFacturacion.css' %}">




     <script>
        $( document ).ready(function() {
           $('.leftmenutrigger').on('click', function(e) {
           $('.side-nav').toggleClass("open");
           $(".ico-nav").toggle();
           e.preventDefault();
          });

          $("#session").click(function(){
            $(".session-item").toggle();
             $('#session').toggleClass("open-session");
          });
          $("#cursos").click(function(){
            $(".cursos-item").toggle();
             $('#cursos').toggleClass("open-cursos");
          });
          
      });


    </script>

</head>

<body>
        

          <!--contenido-->
            <div class="container-fluid">

                {% block content %}
                <body>
                  <div class="row">
                    <div class="col">
                      
                        <div class="card " style="min-height:90vh; background: no-repeat; background-size: cover; background-position: center;">
                            <div class="card-body bg">
                              
                                <!--<img src="#" class="img-fluid d-block mx-auto" style="width:230px">-->
                                <br>
                                Nombre de trayectoria: {{curso_1.name}}
                                
                                {% for path in paths %}
                               
                                  {% if path.course_id == curso_1.id %}
                                  <br>
                                  con path_id: {{path.id}}
                                  <br>
                                  {% for enterprise in enterprises %}
                                    {% if enterprise.id == path.enterprise_id %}
                                      De enterprise : {{enterprise.personal_name}}
                                    {% endif %}
                                  {% endfor %}
                                  <br>
                                  Código de path_step con etapa
                                  <br>
                                  <table style="width:100%">
                                    <thead>
                                      <tr>
                                        <th>ID evaluación o proyecto</th>
                                        <th> Evaluación o proyecto </th>
                                        <th> Competencias asociadas </th>
                                        <th> Numero del path_step</th>
                                        <th> Id del path_step </th>
                                        <th> Step Element order</th>
                                        <th> Actualizar </th>
                                      </tr>
                                      
                                        {% for path_step in path_steps %}

                                          {% if path_step.path.id == path.id %}
                                                      {{ path_step.id }}
                                                     {{ path_step.number}}
                                                     <br>
                                            
                                              {% for step_element in step_elements %}
                                                      
                                              
                                                {% if step_element.path_step.id ==  path_step.id %}
                                                  
                                                  {% for evaluation in evaluations %}

                                                    {% if evaluation.id == step_element.evaluation_id %}
                                                    <tr>
                                                    <td>{{evaluation.id}}</td>
                                                    <td>{{evaluation.name}}</td>
                                                    <td> 
                                                        {% for ec in evaluation_competences %}
                                                          {% if ec.evaluation_id == evaluation.id%}
                                                            {% for competence in competences %}
                                                              {% if competence.id == ec.competence_id%}
                                                                {{ competence.shortname }}
                                                              {% endif %}
                                                            {% endfor %}
                                                          {% endif %}

                                                        {% endfor %}

                                                    </td>
                                                    <td>{{ path_step.number }}</td>
                                                    <td>{{ path_step.id}}</td>
                                                    <td>{{ step_element.order}}</td>                                               
                                                    
                                                    <td class= "adjusted">
                                                        <div class="">
                                                            <a href="#" id='{{step_element.id}}'>
                                                                <button class="btn" onclick = "abrir_modal_edicion('{% url 'etapasApp:actualizar' curso_id=curso_1.id step_id=step_element.id %}')" style="background: transparent; color: green; font-size: 20px;"><i class="fas fa-pencil-alt"></i></button>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    


                                                    {% endif %}

                                                  {% endfor %}
                                                  {% for course in courses %}

                                                    {% if course.id == step_element.course_id %}
                                                    <tr>
                                                    <td>{{course.id}}</td>
                                                    <td>{{course.name}}</td>
                                                    <td> 
                                                        {% for cc in course_competences %}
                                                          {% if cc.course_id == course.id%}
                                                            {% for competence in competences %}
                                                              {% if competence.id == cc.competence_id%}
                                                                {{ competence.shortname }}
                                                              {% endif %}
                                                            {% endfor %}
                                                          {% endif %}

                                                        {% endfor %}

                                                    </td>
                                                    <td>{{ path_step.number }}</td>
                                                    <td>{{ path_step.id}}</td>
                                                    <td>{{ step_element.order}}</td>
                                                    <td class= "adjusted">
                                                        <div class="">
                                                            <a href="#" id='{{step_element.id}}'>
                                                                <button class="btn" onclick = "abrir_modal_edicion('{% url 'etapasApp:actualizar' curso_id=curso_1.id step_id=step_element.id %}')" style="background: transparent; color: green; font-size: 20px;"><i class="fas fa-pencil-alt"></i></button>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    
                                            

                                                    {% endif %}

                                                  {% endfor %}
                                                {% endif %}

                                              {% endfor %}

                                          {% endif %}
                                          
                                        {% endfor %}
                                      </tr>
                                    </thead>
                                  </table>
                                  {% endif %}
                                {% endfor %}
                                
                                
                                
                                <div class="row text-center">
                                  
                                  <div class="col-md-12" style="padding-top: 50%;">
                                    <p class="center frase" style="color: black ;">
                                      
                                       
                                      
                                    </p>
                                  </div>
                              </div>
                                <div class="row abajo">
                                  <div class="col-md-4">
                                  
                                  </div>
                                  
                                  <div class="col-md-4">
                                    
                                  </div>
                              </div>
                            </div>
                        </div>
                    </div>
                  </div>

                </body>

                {% endblock content %}


            </div>


        </div>
        
        <div class="modal fade" id="edicion" role="dialog">
         
    
        </div>

<script type="text/javascript">
    function abrir_modal_edicion(url){
      
        $('#edicion').load(url, function (){
            $(this).modal('show');
        });
    };
    function abrir_modal_creacion(url){
        $('#creacion').load(url, function (){
            $(this).modal('show');
        });
    }
    

</script>

</body>

</html>